### ISSUE TITLE
optimize for mobile

### ISSUE THREAD

**Issue by rmirau** [mobergmann/sport-challenge#11]
<img width="411" alt="image" src="https://github.com/mobergmann/sport-challenge/assets/38428148/60472aee-6af2-4c0f-a4dd-3d38c7a82414">

**Comment by mobergmann** [comment]
We should indeed tackle this issue!  
I would like to see an implementation utilizing [CSS Media Queries](https://internetingishard.netlify.app/html-and-css/responsive-design#css-media-queries). I don't know the best practices and disadvantages/advantages of using the **landscape** and **portrait** CSS Media Queries, but maybe that would be a good approach (or a bad one).

**Comment by rmirau** [comment]
#22
